ProjectMVC/Controllers/HospitalController.cs
using ProjectMVC.Context;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectMVC.Models;

namespace ProjectMVC.Controllers
{
    public class HospitalController : Controller
    {
        HMSEntities db = new HMSEntities();
      



        //*********************************************************************
        // GET: Hospital
        [HttpGet]
        public ActionResult MyProfile()
        {
            if (Session["HID"] == null)
            {
                return RedirectToAction("Login", "LoginAdminHospital");
            }
            int HID = (int)Session["HID"];
            Hospital hospital = db.Hospitals.Where(x => x.ID == HID).FirstOrDefault();
            return View(hospital);
        }
        //***************************************************************************

        [HttpGet]
        public ActionResult EditProfile()
        {
            if (Session["HID"] == null)
            {
                return RedirectToAction("Login", "LoginAdminHospital");
            }
            int HID = (int)Session["HID"];

            Hospital h = db.Hospitals.Where(x => x.ID == HID).FirstOrDefault();
            return View(h);
        }
        [HttpPost]
        public ActionResult EditProfile(Hospital hospital)
        {
            if (Session["HID"] == null)
            {
                return RedirectToAction("Login", "LoginAdminHospital");
            }
            int HID = (int)Session["HID"];
            if (!ModelState.IsValid)
            {
                return View("EditProfile");

            }
           
            try
            {
                var EditHospital = db.Hospitals.Single(x => x.ID == HID);
                EditHospital.Name = hospital.Name;
                EditHospital.NumOfAllBed = hospital.NumOfAllBed;
                // EditHospital.NumOfAvailableBed = hospital.NumOfAvailableBed;
                EditHospital.Phone = hospital.Phone;
                EditHospital.Address = hospital.Address;
                EditHospital.HospitalLongitude = hospital.HospitalLongitude;
                EditHospital.HospitalLatitude = hospital.HospitalLatitude;
                //EditHospital.Logo = hospital.Logo;
                db.SaveChanges();
                return RedirectToAction("MyProfile");
            }
            catch (Exception ex)
            {
                return RedirectToAction("MyProfile");
            }
        }

        //*************************************************************************************
        [HttpGet]
        public ActionResult ShowSpeciality()
        {
            if (Session["HID"] == null)
            {
                return RedirectToAction("Login", "LoginAdminHospital");
            }
            int HID = (int)Session["HID"];

            SpecialityADO speciality = new SpecialityADO();
            // List<Specialty> specialties = db.Specialties.Where(x => x.ID == db.Doctors.Count() && x.SpecialtyID == db.Specialties.ID).Include(x => x.Hospital).ToList();
            List<Specialty> specialties = speciality.FetchAll_Speciality(HID);

            return View(specialties);
        }


        ////****************************************************************************

        [HttpGet]
        public ActionResult ShowReservation(int id)
        {
            if (Session["HID"] == null)
            {
                return RedirectToAction("Login", "LoginAdminHospital");
            }
            int HID = (int)Session["HID"];

            //List<Reservation> re = db.Reservations.Where(x => x.HospitalID == id).Include(p => p.Specialty).Include(x => x.Doctor).Include(y => y.Patient).ToList();

            List<Reservation> re = db.Reservations.Where(x => x.HospitalID == id && x.SpecialtyID == id).Include(p => p.Specialty).Include(y => y.Patient).ToList();
            return View(re);
        }

        [HttpPost]
        public ActionResult ConfirmReservation(int id, bool confirm)
        {
            db.Configuration.ProxyCreationEnabled = false;
            try
            {
                var EditHospital = db.Reservations.Single(x => x.ID == id);
                EditHospital.AdmitOrDecline = confirm;
                db.SaveChanges();
                List<Reservation> response = db.Reservations.Where(x => x.HospitalID == id && x.SpecialtyID == id ).Include(p => p.Specialty).Include(y => y.Patient).ToList();
                return Json(response, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { result = 0 });
            }
            //return Json(new { result = 0 });
        }
        //***********************************************

        [HttpPost]
        public ActionResult Search(string searchTerm)
        {

            List<Hospital> hospitals;
            if (string.IsNullOrEmpty(searchTerm))
            {
                hospitals = db.Hospitals.ToList();
            }
            else
            {
                hospitals = db.Hospitals.Where(s => s.Name.StartsWith(searchTerm)).ToList();
            }
            return View(hospitals);
        }

        //*****************************************************************************
        public ActionResult History(int id)
        {
            if (Session["HID"] == null)
            {
                return RedirectToAction("Login", "LoginAdminHospital");
            }
            List<PatientDoctor> patientDoctors = db.PatientDoctors.Where(p => p.PatientID == id).Include(x => x.Patient).Include(x => x.Doctor).Include(x => x.Illness).ToList();
            return View(patientDoctors);
        }
    }
}

ProjectMVC/Views/Hospital/EditProfile.cshtml
@model ProjectMVC.Context.Hospital

@{
    ViewBag.Title = "EditProfile";
    Layout = "~/Views/Shared/_LayoutHospital.cshtml";
}
<br />
<h2>EditProfile</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Hospital</h4>
    <hr />

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Logo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NumOfAllBed, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NumOfAllBed, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NumOfAllBed, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.HospitalLongitude, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HospitalLongitude, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HospitalLongitude, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.HospitalLatitude, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HospitalLatitude, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HospitalLatitude, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.NumOfAvailableBed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumOfAvailableBed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumOfAvailableBed, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "MyProfile")
</div>

ProjectMVC/Views/Hospital/History.cshtml
@model IEnumerable<ProjectMVC.Context.PatientDoctor>

@{
    ViewBag.Title = "History"; Layout = "~/Views/Shared/_LayoutHospital.cshtml";
}
<br /><br />
<h4 style="">History Of Illness for patient: @Model.ElementAt(0).Patient.Name</h4>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DoctorID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PatientID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IllnessID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Diagnosis)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Doctor.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Illness.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Diagnosis)
            </td>
            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id=item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.ID })
                </td>*@
        </tr>
    }

</table>

ProjectMVC/Views/Hospital/Login.cshtml
@{
    Layout =null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="/fonts/material-icon/css/material-design-iconic-font.min.css  ">

    <!-- Main css -->
    <link rel="stylesheet" href="~/Content/style.css">
</head>
<body>

    <div class="main">

        <!-- Sign up form -->
        <!--
        <section class="signup">
            <div class="container">
                <div class="signup-content">
                    <div class="signup-form">
                        <h2 class="form-title">Sign up</h2>
                        <form method="POST" class="register-form" id="register-form">
                            <div class="form-group">
                                <label for="name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" name="name" id="name" placeholder="Your Name"/>
                            </div>
                            <div class="form-group">
                                <label for="email"><i class="zmdi zmdi-email"></i></label>
                                <input type="email" name="email" id="email" placeholder="Your Email"/>
                            </div>
                            <div class="form-group">
                                <label for="pass"><i class="zmdi zmdi-lock"></i></label>
                                <input type="password" name="pass" id="pass" placeholder="Password"/>
                            </div>
                            <div class="form-group">
                                <label for="re-pass"><i class="zmdi zmdi-lock-outline"></i></label>
                                <input type="password" name="re_pass" id="re_pass" placeholder="Repeat your password"/>
                            </div>
                            <div class="form-group">
                                <input type="checkbox" name="agree-term" id="agree-term" class="agree-term" />
                                <label for="agree-term" class="label-agree-term"><span><span></span></span>I agree all statements in  <a href="#" class="term-service">Terms of service</a></label>
                            </div>
                            <div class="form-group form-button">
                                <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>
                            </div>
                        </form>
                    </div>
                    <div class="signup-image">
                        <figure><img src="~/images/signup-image.jpg" alt="sing up image"></figure>
                        <a href="#" class="signup-image-link">I am already member</a>
                    </div>
                </div>
            </div>
        </section>
        -->
        <!-- Sing in  Form -->
        <section class="sign-in">
            <div class="container">
                <div class="signin-content">
                    <div class="signin-image">
                        <figure><img src="~/images/signin-image.jpg" alt="sing up image"></figure>
                        <a href="#" class="signup-image-link">Create an account</a>
                    </div>

                    <div class="signin-form">
                        <h2 class="form-title">Sign up</h2>
                        <form method="POST" class="register-form" id="login-form">
                            <div class="form-group">
                                <label for="your_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" name="your_name" id="your_name" placeholder="Your Name" />
                            </div>
                            <div class="form-group">
                                <label for="your_pass"><i class="zmdi zmdi-lock"></i></label>
                                <input type="password" name="your_pass" id="your_pass" placeholder="Password" />
                            </div>
                            <div class="form-group">
                                <input type="checkbox" name="remember-me" id="remember-me" class="agree-term" />
                                <label for="remember-me" class="label-agree-term"><span><span></span></span>Remember me</label>
                            </div>
                            <div class="form-group form-button">
                                <input type="submit" name="signin" id="signin" class="form-submit" value="Log in" />
                            </div>
                        </form>
                        <div class="social-login">
                            <span class="social-label">Or login with</span>
                            <ul class="socials">
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-facebook"></i></a></li>
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-twitter"></i></a></li>
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-google"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>

    <!-- JS -->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/Scripts/main.js"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

ProjectMVC/Views/Hospital/MyProfile.cshtml
@model ProjectMVC.Context.Hospital

@{
    ViewBag.Title = "MyProfile";
    Layout = "~/Views/Shared/_LayoutHospital.cshtml";
}

<br />
<h2>MyProfile</h2>

<div>
    <h4>Hospital</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logo)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumOfAllBed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumOfAllBed)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.NumOfAvailableBed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumOfAvailableBed)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.HospitalLongitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HospitalLongitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HospitalLatitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HospitalLatitude)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PAssword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PAssword)
        </dd>*@

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditProfile", new { id = Model.ID }) |

</p>

ProjectMVC/Views/Hospital/ShowReservation.cshtml
@model IEnumerable<ProjectMVC.Context.Reservation>

@{
    Layout = "~/Views/Shared/_LayoutHospital.cshtml";
}


<br />
<h3> All Patient </h3>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ReservationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PatientID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HospitalID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SpecialtyID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOut)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AdmitOrDecline)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.DoctorID)
        </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ReservationDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Patient.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Hospital.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Specialty.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOut)
        </td>

        <td>

            @{
                var x = item.AdmitOrDecline;
                if (x == true)
                { <label class="form-check-label" for="flexCheckDefault">
                        <input class="form-check-input" type="checkbox" id="@item.ID" checked>
                        Confirm Or cancel
                    </label> }
                else
                { <label class="form-check-label" for="flexCheckDefault">
                        <input class="form-check-input" type="checkbox" id="@item.ID">
                        Confirm Or cancel
                    </label>}

            }

        </td>
        <td>
            <button type="button" class="btn btn-primary" onclick="confirmation(@item.ID)">Confirm</button>

        </td>
        <td>
            @*@Html.ActionLink("History Illness", "History", "Hospital",  new { id = item.PatientID @*,type = "button" ,@class="btn btn-primary" })*@
            @Html.ActionLink("History Illness", "History", new { id = item.Patient.ID } , new {  type = "button", @class = "btn btn-primary" })
        </td>
    </tr>
    }

</table>


@Html.ActionLink("Back to Spectiality" , "ShowSpeciality", "Hospital")


@*
<table class="table table-striped table-hover ">
    <thead>
        <tr class="success">
            <th>#</th>
            <th>Column heading</th>
            <th>Column heading</th>
            <th>Column heading</th>
        </tr>
    </thead>
    <tbody id="Accept_Reservation">

    </tbody>
</table>*@

@section Scripts{
    <script>
//        $(document).ready(function () {
////$(document).on('click', '#updatesupplier', function () {
        function confirmation(id) {

           // $(id).click(function () {
                var confirmed;
            if (document.getElementById(id).checked == true) {
                    //var id = $('#confirm').val();
                    confirmed = "True";
                } else {
                    confirmed = "False";
                }
                myData = "id=" + id + "&confirm=" + confirmed;
                $.ajax({
                    type: "POST",
                    url: "http://localhost:62277/Hospital/ConfirmReservation",
                    data: myData,
                    success: function (response) {
                        if (response.result == 0) {
                            alert("Failed ");
                        }
                            alert("success ");
                        $("#Accept_Reservation").empty();
                       // $("#Accept_Reservation").append("<option>Please Select the Illness</option>")

                        response.forEach(function (entry) {
                            //$("#Accept_Reservation").append("<option value =" + entry.ID + ">" + entry.Name + "</option>")
                            $("#Accept_Reservation").append("<tr class='active'> <td>" + entry.PatientID + "</td> <td>" + entry.HospitalID + "</td> <td>" + entry.SpecialtyID + " </td> <td>" + entry.AdmitOrDecline + "</td>  </tr >")

                        });

                    }
                   

                        })

                    }
              
      
    </script>
    }
    @*//$("#HospitalId").change(function () {
        //    Hospital = $(this).val();
        //    $.ajax({
        //        type: "GET",
        //        url: "http://localhost:50960/User/GetSpeciality?id=" + Hospital,

        //        success: function (response) {

        //            $("#SpecialityId").empty();
        //            $("#SpecialityId").append("<option>Please Select the Speciality</option>")

        //            response.forEach(function (entry) {
        //                $("#SpecialityId").append("<option value=" + entry.ID + ">" + entry.Name + "</option>")
        //            });

        //        }
        //    })

        //})

        //// $("#success").show(1000);

        //$("#SpecialityId").change(function () {
        //    Speciality = $(this).val();
        //    Hospital = $('#HospitalId').val();
        //    $.ajax({
        //        type: "GET",
        //        url: "http://localhost:50960/User/GetDoctor?Hid=" + Hospital + "&Sid=" + Speciality,

        //        success: function (response) {

        //            $("#DoctorId").empty();
        //            $("#DoctorId").append("<option>Please Select the Doctor</option>")

        //            response.forEach(function (entry) {
        //                $("#DoctorId").append("<option value=" + entry.ID + ">" + entry.Name + "</option>")
        //            });

        //        }
        //    })

        //})
        //$("#DoctorId").change(function () {
        //    Doctor = $(this).val();
        //    Speciality = $('#SpecialityId').val();
        //    Hospital = $('#HospitalId').val();
        //    $.ajax({
        //        type: "GET",
        //        url: "http://localhost:50960/User/Getschedule?Hid=" + Hospital + "&Sid=" + Speciality + "&Did=" + Doctor,

        //        success: function (response) {

        //            if (response) {
        //                $("#day").empty();
        //                $("#day").append("the scudual start from : " + response.FromDay + " To: " + response.ToDay)
        //            } else {
        //                $("#noday").empty();
        //                $("#noday").append("Sorry! There is no  scudual ")

        //            }

        //        }
        //    })

        //})*@

ProjectMVC/Views/Hospital/ShowSpeciality.cshtml
@model IEnumerable<ProjectMVC.Context.Specialty>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    Layout = "~/Views/Shared/_LayoutHospital.cshtml";
}

<br />
<p>
    @Html.ActionLink("Add New Speciality ", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            <label> Hospital Name</label>
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Hospital.Name)
            </td>*@
            <td>
                @Html.ActionLink("Show All reservations", "ShowReservation", new { id = item.ID }) |

                @*@Html.ActionLink("Delete", "Delete", new { id = item.ID })*@
            </td>
        </tr>
    }

</table>